= JPA/Hibernate camp
:docInfo1
:numbered:
:icons: font
:pagenums:
:imagesdir: images
:source-highlighter: coderay

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg

ifndef::sourcedir[:sourcedir: ./src/main/java/]

#Sample demo to show how jpa work in effiecient way


== Topic

* ElementCollection

@CollectionTable - wskazuje na pole o typie Collection dla którego Hibernate stworzy osobną tabelę
@ElementCollection  - adnotatacja używana do zdefiniowania relacji z typem wbudowanym lub prostym
@IndexColumn -hibernate tworzy oddzielną kolumnę do identyfikowania kolejności wstawianych/wyjmowanych obiektów. 

[source,java]
----
@ElementCollection(fetch=FetchType.LAZY)
@CollectionTable(name = "email")
@IndexColumn(name="email_index")
private List<String> emails;
----
* Persisting Set
Set provides an unordered data structure, and duplicate elements are not allowed. Some
classes implemented by the Set interface are java.util.HashSet , java.util.
LinkedHashSet , and so on.

* Persisting Map


== O mnie
* programista
* blog link:http://przewidywalna-java.blogspot.com[]
* image:{image-link} [role='img-circle']
