== Data Validation


[source,xml]
----
<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator</artifactId>
<version>5.1.0.Alpha1</version>
</dependency>
<!-- these are only necessary if not in a Java EE environment -->
<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator-cdi</artifactId>
<version>5.1.0.Alpha1</version>
</dependency>
<dependency>
<groupId>javax.el</groupId>
<artifactId>javax.el-api</artifactId>
<version>2.2.4</version>
</dependency>

<dependency>
<groupId>org.glassfish.web</groupId>
<artifactId>javax.el</artifactId>
<version>2.2.4</version>
</dependency>
----


== Opis
validation-mode

    By default, Bean Validation (and Hibernate Validator) is activated. When an entity is created, updated (and optionally deleted), it is validated before being sent to the database. The database schema generated by Hibernate also reflects the constraints declared on the entity.

    You can fine-tune that if needed:

        AUTO: if Bean Validation is present in the classpath, CALLBACK and DDL are activated.

        CALLBACK: entities are validated on creation, update and deletion. If no Bean Validation provider is present, an exception is raised at initialization time.

        DDL: (not standard, see below) database schemas are entities are validated on creation, update and deletion. If no Bean Validation provider is present, an exception is raised at initialization time.

        NONE: Bean Validation is not used at all

    Unfortunately, DDL is not standard mode (though extremely useful) and you will not be able to put it in <validation-mode>. To use it, add a regular property


    <property name="javax.persistence.validation.mode">
      ddl
    </property>

    With this approach, you can mix ddl and callback modes:


    <property name="javax.persistence.validation.mode">
      ddl, callback
    </property>


== Własny walidator


== @DecimalMax Numeric     Decimal value less-than or equal to specified value

== @Min    Numeric     Minumum allowed integer value

== @Max    Numeric     Maximum allowed integer value

== @Null   Object  Value must be null

== @NotNull    Object  Value must not be null

== @DecimalMin     Numeric     Decimal value greater-than or equal to specified value

== @Digits     Numeric     Max. number of integer and fraction digits

== @Past   Date    Date must be in the past.

== @Future     Date    Date must be the future

== @AssertFalse    boolean     Value must be false

== @Size   String||Collection||Map||Arrray     Min. and Max. length/size

== @AssertTrue     boolean     Value must be true

== @Pattern    String  Value must match the regular expression 

